[player]
noconsole = "&4You cannot run this command in the console!"
handisempty = "&4You cannot run this command with an empty hand!"

[item]
statvalue = "That stat is set to %value%."
statnewvalue = "&2That stat is now set to %value%."
statsummary = "Here is a summary of stats that have been set on this item:"
nostatsset = "&4Cannot provide a summary because no stats have been set on this item!"
statsreset = "&2All stats on this item have been reset!"
singlestatreset = "&2That stat has been reset!"